name: Build, Test, and Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test Spring Boot Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the project
        run: mvn clean install -DskipTests

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: guidebookx-app
          path: target/*.jar

  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: guidebookx-app
          path: ./build

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-south-1
          application_name: guidebookx
          environment_name: Guidebookx-env
          version_label: ${{ github.sha }}
          deployment_package: ./build/guidebookx-app.jar
          existing_bucket_name: elasticbeanstalk-ap-south-1-058264328131  # Use your S3 bucket name
          wait_for_deployment: true
