name: Build, Test, and Deploy Spring Boot Application

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test Spring Boot Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the project
        run: mvn clean install -DskipTests

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: guidebookx-app
          path: target/*.jar

      - run: echo "Build and Test completed successfully!"

  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: guidebookx-app
          path: .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          region: ap-south-1
          application_name: guidebookx
          environment_name: Guidebookx-env
          version_label: ${{ github.run_id }}
          deployment_package: guidebookx-app.jar
